services:
  app-service:
    build: ./services/app
    container_name: app-service
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${SUPABASE_URL}
  user-service:
    build: ./services/users
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - ENTITY_URL=${ENTITY_URL}
      - USER_URL=${USER_URL}
      - ENV REDIS_PORT=${REDIS_PORT}
      - ENV REDIS_HOST=${REDIS_HOST}
      - ENV REDIS_PASSWORD=${REDIS_PASSWORD}